- templates/app-protect-security-policy.j2
since threat campaigns violations are already enabled in the default policy, removing the redundant config
> removing unneeded config

- CHANGELOG.md
- handlers/main.yml
This prevents some compatibility issues when NGINX App Protect is installed on an instance running NGINX beforehand.
> Tweak handler to have a default state of restarted

- CHANGELOG.md
- defaults/main.yml
- handlers/main.yml
- tasks/install/install-app-protect.yml
Add a `nginx_app_protect_service_modify` variable to revert a breaking change introduced in 0.3.0 where timeouts would not be set by default.
> Systemd tweaks

- CHANGELOG.md
- tasks/install/install-app-protect.yml
- tasks/install/install-debian.yml
- tasks/install/install-redhat.yml
Using `update_cache: true` by itself in the `apt` module is not always idempotent. Moved the NGINX App Protect installation task to a corresponding `apt` or `yum` module to avoid this scenario.
> Fix occasional update_cache idempotence failure

- CHANGELOG.md
- tasks/install/remove-license.yml
Fix a bug related to removing the license from your system and update the Changelog to include the `0.3.1` release date.
> Fix license removal bug and prepare 0.3.1 release

- CHANGELOG.md
- defaults/main.yml
Specify default values for the `nginx_app_protect_license` dictionary to address issue #41 
-   [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx-app-protect/blob/main/CONTRIBUTING.md) document
-   [ ] I have added Molecule tests that prove my fix is effective or that my feature works
-   [X] I have checked that all Molecule tests pass after adding my changes
-   [X] I have updated any relevant documentation (`defaults/main.yml`, `README.md` and `CHANGELOG.md`)
> Add default license vars

- .github/workflows/galaxy.yml
- .github/workflows/molecule.yml
The GitHub actions Molecule CI/CD workflow is no longer run on a new release (this is not necessary since it already runs on every push).
> Do not run Molecule CI/CD workflow when creating a new release

- .github/workflows/molecule.yml
- .github/workflows/requirements/requirements_ansible.yml
- CHANGELOG.md
Update the Ansible `community.general` collection to `2.5.1` and `community.docker` collection to `1.5.0`. And while at it, remove the temporary GitHub actions step to uninstall the Ansible community distribution (it's no longer an Ansible Lint dependency).
> Update Ansible collections

- CHANGELOG.md
- defaults/main.yml
- molecule/default/verify.yml
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
-   [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx-app-protect/blob/main/CONTRIBUTING.md) document
-   [X] I have added Molecule tests that prove my fix is effective or that my feature works
-   [X] I have checked that all Molecule tests pass after adding my changes
-   [X] I have updated any relevant documentation (`defaults/main.yml`, `README.md` and …
> Change default NGINX App Protect conf path for 3.2

- .ansible-lint
- .github/workflows/galaxy.yml
- .github/workflows/molecule.yml
- .github/workflows/release-drafter.yml
- .yamllint
- CHANGELOG.md
- tasks/install/install-debian.yml
Replace "yes"/"no" boolean values with "true"/"false" to comply with YAML spec `1.2`.
> Replace "yes"/"no" boolean values with "true"/"false"

- .ansible-lint
- CHANGELOG.md
- molecule/advanced/requirements.yml
- molecule/default/requirements.yml
- molecule/specific-version/molecule.yml
- molecule/specific-version/requirements.yml
Update `nginx` role requirement in Molecule tests to `0.20.0` and change the `.ansible-lint` config file to avoid installing third party roles as part of the `prerun` process.
> Update `nginx` role requirement in Molecule tests to `0.20.0`

- CHANGELOG.md
- defaults/main.yml
- tasks/install/install-alpine.yml
- tasks/install/install-debian.yml
- tasks/install/install-redhat.yml
This change adds a `nginx_app_protect_manage_repo` boolean which can be used to disable Nginx App Protect repo management by this role.
This feature flag addresses edge-cases where Nginx' App Protect repositories are managed by other means and should not be configured by this role in order to install Nginx App Protect. The default behavior of the role is unaltered.
Sidenote on …
> Add 'nginx_app_protect_manage_repo' feature flag and defaults

- tasks/install/install-redhat.yml
Extends PR #108, setting the `nginx_app_protect_manage_repo` flag on the RHEL _NGINX Plus repository_ task which was erroneously omitted from that PR.
> nginx_app_protect_manage_repo flag for RHEL NGINX Plus repository

- CHANGELOG.md
- molecule/default/prepare.yml
- tasks/common/install/remove-license.yml
The license and repo removal step was failing due to a bug introduced in the role refactoring when adding NAP DoS.
-   [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/ansible-role-nginx-app-protect/blob/main/CONTRIBUTING.md) document
-   [X] I have updated any relevant documentation (`defaults/main.yml`, `README.md` and `CHANGELOG.md`)
> Fix license removal step

- .github/dependabot.yml
Change the Dependabot dependency checks to weekly from daily to make update frequency more sustainable.
> Change dependency checks to weekly

- CHANGELOG.md
- tasks/common/keys/setup-keys.yml
- tasks/main.yml
- vars/main.yml
ENHANCEMENTS:
Add signing keys to a unique NGINX keyring on Debian based systems.
BUG FIXES:
License and keys should now be correctly setup when neither signatures or threat campaigns are installed.
> Still setup key/license when neither signatures/threats are installed

- CHANGELOG.md
- handlers/main.yml
Ansible check mode runs will no longer fail if NGINX has not yet been installed.
> Ansible check mode fails if NGINX is not installed

- CHANGELOG.md
- defaults/main.yml
- molecule/advanced/converge.yml
- templates/services/nginx.service.override.conf.j2
The `nginx_app_protect_timeout` setting previous only applied to service stop operations. This parameter has been changed to `nginx_app_protect_timeoutstopsec` to better reflect its usage, and a new parameter, `nginx_app_protect_timeoutstartsec` has been introduced to tweak service start operation timeouts.
> Add `TimeoutStartSec` parameter

- .github/workflows/requirements/requirements_ansible.yml
- CHANGELOG.md
- README.md
- molecule/advanced/prepare.yml
- molecule/specific-version/converge.yml
- molecule/specific-version/verify.yml
- molecule/uninstall/prepare.yml
- tasks/common/config/configure-app-protect.yml
- tasks/common/prerequisites/install-dependencies.yml
Bump the Ansible `community.general` collection to `5.5.0` and `community.docker` collection to `3.1.0`, and address Linter warnings.
> Bump Ansible collections

- .github/workflows/requirements/requirements_ansible.yml
- CHANGELOG.md
- README.md
- molecule/dos/molecule.yml
- tasks/common/install/setup-license.yml
- tasks/common/keys/setup-keys.yml
- tasks/common/prerequisites/install-dependencies.yml
- tasks/dos/install-alpine.yml
- vars/main.yml
* Add support for Alpine Linux for NGINX App Protect DoS.
* Add support for Debian bullseye for NGINX App Protect DoS.
* Check NGINX App Protect license is valid before trying to install NGINX App Protect (this means the role now requires the `community.crypto` collection).
> Add support for new NAP DoS distros

- .github/workflows/galaxy.yml
- .github/workflows/molecule.yml
- .github/workflows/release-drafter.yml
- CHANGELOG.md
- molecule/advanced/molecule.yml
- molecule/common/Dockerfile.j2
- molecule/default/converge.yml
- molecule/default/molecule.yml
- molecule/dos/molecule.yml
- molecule/specific-version/molecule.yml
- molecule/uninstall/molecule.yml
Update GitHub actions to run on Ubuntu 22.04 (and thus support `cgroups` v2).
> Update GitHub actions to use Ubuntu 22.04

- CHANGELOG.md
- molecule/advanced/molecule.yml
- molecule/default/molecule.yml
- molecule/dos/molecule.yml
- molecule/specific-version/molecule.yml
- molecule/uninstall/molecule.yml
Explicitly specify `amd64` as the platform used in Molecule tests. This will ensure that tests work as expected when run on different host architectures (e.g. newer Macbooks with `arm` processors).
> Use `amd64` platform for Molecule tests

- CHANGELOG.md
- tasks/common/prerequisites/validate-supported-os.yml
- tasks/main.yml
Refactor how this role checks if your distribution is supported NGINX App Protect. The role will no longer fail if the  target distribution is not supported, instead, you will get a warning. This should help with the occasional lag between new releases of distributions and/or NGINX App Protect and this role being updated to support those releases.
> Refactor how supported distributions are checked

- .ansible-lint
- .github/release-drafter.yml
- .github/workflows/galaxy.yml
- .github/workflows/molecule.yml
- .github/workflows/requirements/requirements_ansible.yml
- .github/workflows/requirements/requirements_ansible_lint.txt
- .github/workflows/requirements/requirements_galaxy.txt
- .github/workflows/requirements/requirements_molecule.txt
- CHANGELOG.md
- molecule/advanced/molecule.yml
- molecule/common/cleanup.yml
- molecule/default/molecule.yml
- molecule/default/verify.yml
- molecule/dos/molecule.yml
- molecule/specific-version/molecule.yml
- molecule/uninstall/molecule.yml
- tasks/common/install/setup-license.yml
ENHANCEMENTS:
- Bump the Ansible `ansible.posix` collection to `1.5.4`, `community.general` collection to `6.4.0`, `community.crypto` collection to `2.14.1` and `community.docker` collection to `3.4.7`.
- Oracle Linux 8 requires the Python `python3.11-cryptography` package for validating the NGINX App Protect repository certificate.
CI/CD:
- Split Ansible Lint into its own GitHub Actions job since Molecule no longer runs linters natively.
- Replace `molecule[docker]` with `molecule` and `molecule-plugins[docker]`.
- Add pre-releases to Release Drafter.
> Bring CI/CD up to date and resolve minor Python 3 cryptography issue

- .github/CODEOWNERS
- CHANGELOG.md
- README.md
- defaults/main.yml
- meta/main.yml
- molecule/advanced/molecule.yml
- molecule/common/Dockerfile.j2
- molecule/default/molecule.yml
- molecule/dos/molecule.yml
- molecule/specific-version/molecule.yml
- molecule/uninstall/molecule.yml
- tasks/common/keys/setup-keys.yml
- tasks/common/prerequisites/install-dependencies.yml
- tasks/common/prerequisites/setup-selinux.yml
- tasks/common/validate/validate.yml
- tasks/dos/install-redhat.yml
- tasks/waf/install-redhat.yml
- vars/main.yml
- Remove support for RHEL 7 based distributions (RHEL/CentOS/Oracle Linux 7) given CentOS 7 has reached EoL, RHEL 7 has reached EoM, and Oracle Linux 7 will reach EoL shortly.
- Remove support for installing NGINX App Protect WAF/DoS on Alpine Linux 3.15/3.16 and Ubuntu bionic.
> chore!: Remove support for RHEL 7 based distributions

- CHANGELOG.md
- molecule/default/molecule.yml
- molecule/dos/molecule.yml
- molecule/uninstall/molecule.yml
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
> feat: Install NAP on all supported platforms

- tasks/common/prerequisites/install-dependencies.yml
- vars/main.yml
The EPEL 7 repo is no longer active, so we need to update the Amazon Linux 2 EPEL task to use the Amazon Linux 2 EPEL extras repo instead.
> fix: EPEL is no longer active on RHEL 7 based distros
